spring:
  datasource:
    url: jdbc:mysql://localhost/yang?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  thymeleaf:
    cache: false
    prefix: classpath:/html/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html